"""empty message

Revision ID: 33c104fea16d
Revises: b50443a8f342
Create Date: 2016-09-28 10:36:59.971000

"""

# revision identifiers, used by Alembic.
revision = '33c104fea16d'
down_revision = 'b50443a8f342'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_books_isbn', table_name='books')
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.create_index('ix_books_isbn', 'books', ['isbn'], unique=False)
    ### end Alembic commands ###
