"""empty message

Revision ID: 641ded487d6a
Revises: e59b2cb18c2e
Create Date: 2016-10-03 23:37:26.727000

"""

# revision identifiers, used by Alembic.
revision = '641ded487d6a'
down_revision = 'e59b2cb18c2e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('status', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_books_status'), 'books', ['status'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_status'), table_name='books')
    op.drop_column('books', 'status')
    ### end Alembic commands ###
