"""empty message

Revision ID: e59b2cb18c2e
Revises: 33c104fea16d
Create Date: 2016-09-30 22:10:05.213000

"""

# revision identifiers, used by Alembic.
revision = 'e59b2cb18c2e'
down_revision = '33c104fea16d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('imagepath', sa.String(length=140), nullable=True))
    op.create_index(op.f('ix_users_imagepath'), 'users', ['imagepath'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_imagepath'), table_name='users')
    op.drop_column('users', 'imagepath')
    ### end Alembic commands ###
